"""Conservative deterministic extraction used only when model extraction fails."""

from __future__ import annotations

import re
from collections.abc import Iterator

from .schemas import ExtractionChange, ExtractionDraft


def _change(
    path: str,
    value: str | int | float | list[str],
    unit: str | None,
    evidence: str,
) -> ExtractionChange:
    return ExtractionChange.model_validate(
        {
            "path": path,
            "value": value,
            "unit": unit,
            "certainty": "needs_confirmation",
            "evidence": evidence,
            "note": "모델 실패 후 제한된 규칙으로 추출됨",
        }
    )


def _structured_mobile_template(transcript: str) -> list[ExtractionChange]:
    """Parse only the exact sentences generated by MobileApp's structured form.

    This is deliberately not a general Korean clinical parser. It exists so a
    manually completed local form still crosses the same proposal/HITL boundary
    when the model path is unavailable.
    """

    initial = re.fullmatch(
        r"환자 접촉 후 초기 평가입니다\. 기도 (?P<airway>개방|확보 필요), "
        r"호흡 (?P<breathing>자발호흡|호흡 이상), "
        r"순환 (?P<circulation>맥박 촉지|순환 불안정)입니다\. "
        r"의식수준은 AVPU (?P<avpu>[AVPU])입니다\. "
        r"주호소는 (?P<complaint>.{1,200})입니다\.",
        transcript,
    )
    if initial:
        return [
            _change("assessment.airway", initial.group("airway"), None, initial.group("airway")),
            _change("assessment.breathing", initial.group("breathing"), None, initial.group("breathing")),
            _change(
                "assessment.circulation",
                initial.group("circulation"),
                None,
                initial.group("circulation"),
            ),
            _change("consciousness.avpu", initial.group("avpu"), None, f"AVPU {initial.group('avpu')}"),
            _change(
                "symptoms.chiefComplaint",
                initial.group("complaint"),
                None,
                initial.group("complaint"),
            ),
        ]

    focused = re.fullmatch(
        r"증상 발생시각은 (?P<onset>[0-2]\d:[0-5]\d)입니다\. "
        r"흉통은 NRS (?P<nrs>10|[0-9]), (?P<quality>[^,.]{1,60}) 양상이며 "
        r"방사통은 (?P<radiation>[^.]{1,60})입니다\. "
        r"동반증상은 (?P<associated>[^.]{1,200})입니다\. "
        r"과거력은 (?P<history>[^,]{1,200}), 복용약은 (?P<medication>[^,]{1,200}), "
        r"알레르기는 (?P<allergy>[^.]{1,200})입니다\.",
        transcript,
    )
    if focused:
        associated = [item.strip() for item in re.split(r"[,·]", focused.group("associated")) if item.strip()]
        changes = [
            _change("symptoms.onsetAt", focused.group("onset"), None, focused.group("onset")),
            _change("symptoms.chestPainNrs", int(focused.group("nrs")), None, f"NRS {focused.group('nrs')}"),
            _change(
                "symptoms.chestPainQuality",
                focused.group("quality"),
                None,
                focused.group("quality"),
            ),
            _change(
                "symptoms.chestPainRadiation",
                focused.group("radiation"),
                None,
                focused.group("radiation"),
            ),
            _change("symptoms.associated", associated, None, focused.group("associated")),
        ]
        optional_fields = (
            ("history.conditions", "history"),
            ("history.medications", "medication"),
            ("history.allergies", "allergy"),
        )
        for path, group in optional_fields:
            value = focused.group(group)
            if value != "미확인":
                changes.append(_change(path, [value], None, value))
        return changes

    vitals = re.fullmatch(
        r"최초 활력징후는 혈압 (?P<sbp>\d{2,3})/(?P<dbp>\d{2,3}) mmHg, "
        r"맥박 (?P<pulse>\d{1,3})회/분, 호흡수 (?P<rr>\d{1,2})회/분, "
        r"산소포화도 (?P<spo2>\d{1,3})%, 체온 (?P<temperature>\d{2}(?:\.\d+)?)도, "
        r"혈당 (?P<glucose>\d{1,4}) mg/dL입니다\. 시행 처치는 (?P<treatment>[^.]{1,200})입니다\.",
        transcript,
    )
    if vitals:
        changes = [
            _change("vitals.systolicBp", int(vitals.group("sbp")), "mmHg", vitals.group("sbp")),
            _change("vitals.diastolicBp", int(vitals.group("dbp")), "mmHg", vitals.group("dbp")),
            _change("vitals.pulse", int(vitals.group("pulse")), "/min", vitals.group("pulse")),
            _change("vitals.respiratoryRate", int(vitals.group("rr")), "/min", vitals.group("rr")),
            _change("vitals.spo2", int(vitals.group("spo2")), "%", vitals.group("spo2")),
            _change(
                "vitals.temperature",
                float(vitals.group("temperature")),
                "°C",
                vitals.group("temperature"),
            ),
            _change("vitals.glucose", int(vitals.group("glucose")), "mg/dL", vitals.group("glucose")),
        ]
        treatment = vitals.group("treatment")
        changes.append(_change("treatment.procedures", [treatment], None, treatment))
        return changes

    return []


def _numeric_matches(transcript: str) -> Iterator[ExtractionChange]:
    patterns: tuple[tuple[str, re.Pattern[str], str | None, type[int] | type[float]], ...] = (
        (
            "vitals.pulse",
            re.compile(r"(?:맥박|심박수|HR)\s*(?:은|는|이|가)?\s*(\d{2,3})", re.IGNORECASE),
            "/min",
            int,
        ),
        (
            "vitals.respiratoryRate",
            re.compile(r"(?:호흡수|RR)\s*(?:은|는|이|가)?\s*(\d{1,2})", re.IGNORECASE),
            "/min",
            int,
        ),
        (
            "vitals.spo2",
            re.compile(
                r"(?:산소\s*포화도|SpO2|SpO₂)\s*(?:은|는|이|가)?\s*(\d{2,3})\s*(?:%|퍼센트)?",
                re.IGNORECASE,
            ),
            "%",
            int,
        ),
        (
            "vitals.temperature",
            re.compile(r"(?:체온|BT)\s*(?:은|는|이|가)?\s*(\d{2}(?:\.\d+)?)", re.IGNORECASE),
            "°C",
            float,
        ),
        (
            "vitals.glucose",
            re.compile(r"(?:혈당|BST)\s*(?:은|는|이|가)?\s*(\d{2,3})", re.IGNORECASE),
            "mg/dL",
            int,
        ),
    )
    for path, pattern, unit, caster in patterns:
        for match in pattern.finditer(transcript):
            yield _change(path, caster(match.group(1)), unit, match.group(0))


def deterministic_fallback(transcript: str) -> ExtractionDraft:
    """Extract only tightly formatted demographics, AVPU, and vital signs.

    The fallback deliberately does not infer symptoms, diagnoses, treatments, or hospitals.
    The last explicit mention of a field wins, and every value remains needs_confirmation.
    """

    candidates: list[ExtractionChange] = []

    candidates.extend(_structured_mobile_template(transcript))

    for match in re.finditer(
        r"(?P<age>\d{2,3})\s*세\s*(?P<sex>남성|남자|여성|여자)", transcript
    ):
        sex = "male" if match.group("sex") in {"남성", "남자"} else "female"
        candidates.extend(
            [
                _change("patient.age", int(match.group("age")), "years", match.group(0)),
                _change("patient.sex", sex, None, match.group(0)),
            ]
        )

    for match in re.finditer(
        r"(?:혈압|BP)\s*(?:은|는|이|가)?\s*(\d{2,3})\s*(?:/|에)\s*(\d{2,3})",
        transcript,
        re.IGNORECASE,
    ):
        candidates.extend(
            [
                _change("vitals.systolicBp", int(match.group(1)), "mmHg", match.group(0)),
                _change("vitals.diastolicBp", int(match.group(2)), "mmHg", match.group(0)),
            ]
        )

    candidates.extend(_numeric_matches(transcript))

    for match in re.finditer(r"AVPU\s*(?:는|은|이|가)?\s*([AVPU])\b", transcript, re.IGNORECASE):
        candidates.append(_change("consciousness.avpu", match.group(1).upper(), None, match.group(0)))

    latest_by_path: dict[str, ExtractionChange] = {}
    for candidate in candidates:
        latest_by_path[candidate.path] = candidate
    return ExtractionDraft(changes=list(latest_by_path.values()), unknowns=[])
